Ban worker from sidekiq job class name descendants
g2crowd/rubocop-g2 pull request #10
Opened 2021-12-23 20:10 UTC by sarodspirit

Ban worker from sidekiq job class name descendants

2021-12-23 20:30 UTC, hasghari requested changes

2021-12-23 20:30 UTC, hasghari commented on spec/rubocop/cop/g2/ban_worker_term_spec.rb
> +      class FooWorker < Sidekiq::Worker
`Sidekiq::Worker` is a module so it cannot be subclassed, it needs to be included:
```suggestion
      class FooWorker
        include Sidekiq::Worker
```

2021-12-24 14:15 UTC, hasghari requested changes

2021-12-24 14:15 UTC, hasghari commented on spec/rubocop/cop/g2/ban_worker_term_spec.rb
> +      class FooJob; include Sidekiq::Worker
We don't really care what the class name is, so this should also be registered as an offense. The rule is very simple, `Sidekiq::Worker` should never be included in any class, regardless of the name.

2021-12-27 11:24 UTC, sarodspirit commented on spec/rubocop/cop/g2/ban_worker_term_spec.rb
> +      class FooJob; include Sidekiq::Worker
Maybe I understood incorrectly but I thought the whole point of this was to discourage the use of Worker term in classnames as sidekiq recommends to use Job.
I see several classes in our domain that include [Sidekiq::Worker](https://github.com/g2crowd/ue/search?q=Sidekiq%3A%3AWorker).

2022-01-03 14:54 UTC, hasghari commented on spec/rubocop/cop/g2/ban_worker_term_spec.rb
> +      class FooJob; include Sidekiq::Worker
My pull request [here](https://github.com/g2crowd/ue/pull/20569) swaps out `Sidekiq::Worker` for `Sidekiq::Job` so the rule to prevent the use of `Sidekiq::Worker` should be sufficient.

2022-01-03 20:47 UTC, hasghari approved these changes
nice job!

2022-01-04 00:22 UTC, hasghari requested changes

2022-01-04 00:22 UTC, hasghari commented on lib/rubocop/cop/g2/ban_sidekiq_worker.rb
> +        def on_class(node)
This is a minor nitpick but do you mind changing this to `on_send` instead?
```suggestion
        def on_send(node)
```
I think it's a bit nicer for error highlighting because it doesn't highlight the class keyword the the class name, just the `include` statement.

2022-01-04 16:17 UTC, sarodspirit commented on lib/rubocop/cop/g2/ban_sidekiq_worker.rb
> +        def on_class(node)
Nice, I'll do change it.

2022-01-04 17:09 UTC, hasghari approved these changes
LGTM

2022-01-04 17:11 UTC, merged